language: generic
sudo: required
services:
  - docker

notifications:
  slack: privateuser-workspace:5hybgvvnXJOVAuc01WiKfrmX

before_install:
  - docker build -t adriankubica/docker-react -f Dockerfile.dev .

script:
  - docker run adriankubica/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-844735237674"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
