language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adriankubica/docker-react -f Dockerfile.dev .

script:
  - docker run adriankubica/docker-react npm run test -- --coverage